version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: heroes_factory
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  
  mysql-test:
    image: mysql:8
    container_name: mysql-test
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: heroes_factory_test
    ports:
      - "3307:3306"

volumes:
  mysql-data: